In [2]:
import torch
print(torch.__version__)

2.6.0+cu124


In [3]:
# Creating a 0-D Tensor (Scalar)
scalar_tensor = torch.tensor(7)
print("Scalar Tensor:", scalar_tensor)
print("Dimensions (rank):", scalar_tensor.ndim)
print("Shape:", scalar_tensor.shape)

# Creating a 1-D Tensor (Vector)
vector_tensor = torch.tensor([1, 2, 3, 4, 5])
print("\nVector Tensor:", vector_tensor)
print("Dimensions (rank):", vector_tensor.ndim)
print("Shape:", vector_tensor.shape)

# Creating a 2-D Tensor (Matrix)
matrix_tensor = torch.tensor([[10, 20, 30],
                              [40, 50, 60]])
print("\nMatrix Tensor:\n", matrix_tensor)
print("Dimensions (rank):", matrix_tensor.ndim)
print("Shape:", matrix_tensor.shape)

# Creating a 3-D Tensor (Example)
# This could represent 2 images, each 3x3 pixels (e.g., grayscale)
tensor_3d = torch.tensor([
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]],

    [[11, 12, 13],
     [14, 15, 16],
     [17, 18, 19]]
])
print("\n3D Tensor:\n", tensor_3d)
print("Dimensions (rank):", tensor_3d.ndim)
print("Shape:", tensor_3d.shape)

Scalar Tensor: tensor(7)
Dimensions (rank): 0
Shape: torch.Size([])

Vector Tensor: tensor([1, 2, 3, 4, 5])
Dimensions (rank): 1
Shape: torch.Size([5])

Matrix Tensor:
 tensor([[10, 20, 30],
        [40, 50, 60]])
Dimensions (rank): 2
Shape: torch.Size([2, 3])

3D Tensor:
 tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[11, 12, 13],
         [14, 15, 16],
         [17, 18, 19]]])
Dimensions (rank): 3
Shape: torch.Size([2, 3, 3])


In [4]:
# Addition
tensor_A = torch.tensor([1, 2, 3])
tensor_B = torch.tensor([4, 5, 6])
print("Tensor A + B:", tensor_A + tensor_B)

# Multiplication (element-wise)
print("Tensor A * B (element-wise):", tensor_A * tensor_B)

# Matrix Multiplication (dot product - CRUCIAL for neural networks)
# For matrix multiplication, inner dimensions must match: (a, b) @ (b, c) -> (a, c)
matrix1 = torch.tensor([[1, 2], [3, 4]])
matrix2 = torch.tensor([[5, 6], [7, 8]])
print("\nMatrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)
print("Matrix Multiplication (torch.matmul):\n", torch.matmul(matrix1, matrix2))
print("Matrix Multiplication (using @ operator):\n", matrix1 @ matrix2) # Python 3.5+ operator for matmul

# Reshaping Tensors (changing their shape)
# view() or reshape() are common
original_tensor = torch.rand(4, 4)
print("\nOriginal Tensor (4x4):\n", original_tensor)
reshaped_tensor = original_tensor.view(16) # Reshape to a 1D tensor of 16 elements
print("Reshaped to 1D (16 elements):\n", reshaped_tensor)
reshaped_tensor_2x8 = original_tensor.view(2, 8) # Reshape to 2 rows, 8 columns
print("Reshaped to 2x8:\n", reshaped_tensor_2x8)

Tensor A + B: tensor([5, 7, 9])
Tensor A * B (element-wise): tensor([ 4, 10, 18])

Matrix 1:
 tensor([[1, 2],
        [3, 4]])
Matrix 2:
 tensor([[5, 6],
        [7, 8]])
Matrix Multiplication (torch.matmul):
 tensor([[19, 22],
        [43, 50]])
Matrix Multiplication (using @ operator):
 tensor([[19, 22],
        [43, 50]])

Original Tensor (4x4):
 tensor([[0.8266, 0.6227, 0.0442, 0.7190],
        [0.6364, 0.8463, 0.3466, 0.7299],
        [0.2924, 0.3495, 0.2514, 0.0159],
        [0.3356, 0.8403, 0.2879, 0.5614]])
Reshaped to 1D (16 elements):
 tensor([0.8266, 0.6227, 0.0442, 0.7190, 0.6364, 0.8463, 0.3466, 0.7299, 0.2924,
        0.3495, 0.2514, 0.0159, 0.3356, 0.8403, 0.2879, 0.5614])
Reshaped to 2x8:
 tensor([[0.8266, 0.6227, 0.0442, 0.7190, 0.6364, 0.8463, 0.3466, 0.7299],
        [0.2924, 0.3495, 0.2514, 0.0159, 0.3356, 0.8403, 0.2879, 0.5614]])


In [5]:
# Check if CUDA (NVIDIA GPU support) is available
if torch.cuda.is_available():
    print("\nGPU (CUDA) is available! Moving tensors to GPU.")
    device = "cuda"
else:
    print("\nGPU (CUDA) not available, using CPU.")
    device = "cpu"

# Create a tensor on the CPU
cpu_tensor = torch.tensor([1, 2, 3])
print("\nCPU Tensor:", cpu_tensor, cpu_tensor.device)

# Move the tensor to the GPU (if available)
gpu_tensor = cpu_tensor.to(device)
print("GPU Tensor:", gpu_tensor, gpu_tensor.device)

# You can now perform operations on the GPU tensor
gpu_result = gpu_tensor * 10
print("GPU Result:", gpu_result)

# IMPORTANT: You cannot perform operations between tensors on different devices.
# If you have a CPU tensor and a GPU tensor, one must be moved to the other's device.
# For example, to move GPU tensor back to CPU:
# cpu_result = gpu_result.to("cpu")


GPU (CUDA) is available! Moving tensors to GPU.

CPU Tensor: tensor([1, 2, 3]) cpu
GPU Tensor: tensor([1, 2, 3], device='cuda:0') cuda:0
GPU Result: tensor([10, 20, 30], device='cuda:0')


In [6]:
import torch.nn as nn
import torch.nn.functional as F

# 1. Define your neural network architecture
class SimpleNeuralNetwork(nn.Module):
    def __init__(self):
        super(SimpleNeuralNetwork, self).__init__()
        # Define layers: an input layer to a hidden layer, then hidden to output
        self.fc1 = nn.Linear(in_features=10, out_features=50) # Fully Connected Layer 1
        self.fc2 = nn.Linear(in_features=50, out_features=1) # Fully Connected Layer 2 (output)

    def forward(self, x):
        # Define how data flows through the network
        x = F.relu(self.fc1(x)) # Apply linear layer, then a non-linear activation (ReLU)
        x = torch.sigmoid(self.fc2(x)) # Apply output layer, then a sigmoid for binary classification
        return x

# 2. Create an instance of your model and move it to GPU
model = SimpleNeuralNetwork().to(device) # device from previous GPU check

# 3. Define a Loss Function (how "wrong" your model's predictions are)
# For binary classification, Binary Cross Entropy Loss is common
loss_fn = nn.BCELoss()

# 4. Define an Optimizer (how the model updates its weights to reduce loss)
# Adam is a popular choice
optimizer = torch.optim.Adam(model.parameters(), lr=0.001) # lr = learning rate

# 5. Training Loop (Conceptual - this is the core of learning)
# For a real project, you'd have actual data, loop through epochs, batches, etc.
# For now, imagine:
# for epoch in range(num_epochs):
#     for batch in training_data:
#         inputs, targets = batch
#         inputs, targets = inputs.to(device), targets.to(device) # Move data to GPU

#         optimizer.zero_grad() # Clear previous gradients
#         outputs = model(inputs) # Forward pass: make predictions
#         loss = loss_fn(outputs, targets) # Calculate how wrong predictions are
#         loss.backward() # Backward pass: calculate gradients (how much each weight contributed to error)
#         optimizer.step() # Update model weights based on gradients
#
#     # After each epoch, evaluate on validation data
#     # (Not shown here for simplicity)

print("\nConceptual Neural Network defined and ready for training!")
print("Model structure:\n", model)


Conceptual Neural Network defined and ready for training!
Model structure:
 SimpleNeuralNetwork(
  (fc1): Linear(in_features=10, out_features=50, bias=True)
  (fc2): Linear(in_features=50, out_features=1, bias=True)
)
